#!zsh

declare F="${1}"
declare X="${2}"
declare -a T
: ${(A)T::=${${${(ps:\n#:)${${"$(<$F)"}%# Code*}#\#}}}}
: ${(A)T::=${T# }}

cat <<EOT
${${T[2]}[1,-2]} 
$(repeat ${#${T[2]}[1,-2]} do; print -n -- "$X"; done)

${T[3]}

${${T[4]}[1,-2]}

${T[5,-1]}
$(git show todo:./README.asciidoc.in)
EOT
